MVC/HandsOn/HandsOnHelperMethods/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HandsOnHelperMethods.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
      
        public string Designation { get; set; }
        [DataType(DataType.Date)]
        public DateTime JoinDate { get; set; }
        public int Salary { get; set; }

    }
}

MVC/HandsOn/HandsOnHelperMethods/Controllers/AuthenticateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HandsOnHelperMethods.Controllers
{
    public class AuthenticateController : Controller
    {
        // GET: Authenticate
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Validate(string Uname,string Pwd)
        {
            if(Uname=="Virat" &&  Pwd=="12345")
            {
                return RedirectToAction("Welcome");
            }
            else
            {
                ViewBag.Error = "Invalid Credentials";
                return View("Login"); //stay in the Login View
            }
        }
    }
}

MVC/HandsOn/HandsOnHelperMethods/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HandsOnHelperMethods.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC/HandsOn/HandsOnHelperMethods/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HandsOnHelperMethods.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
    }
}

MVC/HandsOn/HandsOnHelperMethods/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HandsOnHelperMethods.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC/HandsOn/HandsOnHelperMethods/Views/Authenticate/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <div> 
        @using(Html.BeginForm("Validate","Authenticate","POST"))
            {
                    <table>
                        <tr>
                            <td>UserName</td>
                            <td>
                                @Html.TextBox("Uname",null,new {})
                            </td>
                        </tr>
                        <tr>
                            <td>Password</td>
                            <td>
                                @Html.Password("Pwd")
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <input type="submit" value="SingIn" />
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                @ViewBag.Error
                            </td>
                        </tr>
                    </table>
            }
    </div>
</body>
</html>

MVC/HandsOn/HandsOnHelperMethods/Views/Demo/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1 class="text-primary">Today Date: @System.DateTime.Now</h1>
</div>